@startuml
digraph CopyrightOnto_CreationLifeCycleSampleMusic {
  node [shape=box; fontname="Arial"];
  edge [fontname="Arial"];
  compound=true; newrank=true;

  subgraph cluster_left { style=invis;
    "Work:\nmusic work";
    "Instance:\nsheet music print";
    "Recording:\nmaster";
  }
  subgraph cluster_right { style=invis;
    "Manifestation:\ncomposition";
    "Performance:\nstudio play";
    "Communication:\nwebcast";
  }
  {rank=same "Work:\nmusic work" "Manifestation:\ncomposition"}
  {rank=same "Instance:\nsheet music print" "Performance:\nstudio play"}
  {rank=same "Recording:\nmaster" "Communication:\nwebcast"}

  "Work:\nmusic work" -> "Manifestation:\ncomposition" [label="is manifestation of", dir=back]
  "Manifestation:\ncomposition" -> "Instance:\nsheet music print" [label="has instance"]
  "Manifestation:\ncomposition" -> "Performance:\nstudio play" [label="has performance"]
  "Performance:\nstudio play" -> "Recording:\nmaster" [label="has recording"]
  "Recording:\nmaster" -> "Communication:\nwebcast" [label="has communication"]
}
@enduml
