@startuml
digraph CreationLifeCycleSample {
  node [shape=box; fontname="Arial"];
  edge [fontname="Arial"];
  nodesep=0.5; ranksep=0.5

  "music work" -> "composition" -> "studio play" -> "master" -> "webcast"
  "composition" -> "sheet music print"

  {rank=same "music work" "composition" "studio play" "master" "webcast"}
  {rank=same "sheet music print"}
}
@enduml
