@startuml
digraph FRBR_CreationModel {
  node [shape=box]
  rankdir=LR
  {rank=same "Work" "Manifestation"}
  {rank=same "Expression" "Item"}
  "Work" -> "Expression" [label="is realized through"]
  "Expression" -> "Manifestation" [label="is embodied in"]
  "Manifestation" -> "Item" [label="is exemplified by"]
}
@enduml