@startuml
digraph MVCO_CreationModel {
  node [shape=box; fontname="Arial"];
  edge [fontname="Arial"];
  rankdir=LR;

  "Work" -> "Manifestation" -> "Instance" -> "Copy"
  "Work" -> "Adaptation" -> "Manifestation"
}
@enduml
