@startuml
digraph OntologyX_CreationModel {
  node [shape=box; fontname="Arial"];
  edge [fontname="Arial"];
  rankdir=LR; ranksep=0.3; nodesep=0.1;

  "Expression" -> "Manifestation" [label="fixed in"]
  "Manifestation" -> "Abstraction" [label="abstracted to"]
  "Abstraction" -> "Expression" [label="expressed in"]
  "Expression" -> "Abstraction" [label="abstracted to"]
  "Abstraction" -> "Manifestation" [label="fixed in"]
}
@enduml
