@startuml
digraph CreationLifeCycleSample {
  node [shape=box]; rankdir=LR

  "Copyright" -> "Economic Rights", "Moral Rights", "Related Rights";

  "Economic Rights" -> "Reproduction Right", "Distribution Right", "Public Performance Right", "Fixation Right", "Communication Right", "Transformation Right";
  "Moral Rights" -> "Attribution Right", "Integrity Right", "Disclosure Right", "Withdrawal Right";
  "Related Rights" -> "Performers Rights", "Phonograms Producers Rights", "Broadcasters Rights"

  "Fixation Right" -> "Sound Recording Right", "Motion Picture Right";
  "Communication Right" -> "Broadcasting Right", "Making Available Right";
  "Transformation Right" -> "Adaptation Right", "Translation Right";
  "Distribution Right" -> "Rental Right", "Importation Right";
}
@enduml